import streamlit as st
import requests

st.title("RAG-Powered Survey Analysis")

# Input for the user query
user_query = st.text_input("Enter your query")

def get_insight_from_backend(user_query):
    response = requests.post(
        "http://127.0.0.1:8000/generate-insight/",
        json={"user_query": user_query}
    )
    return response.json()


if st.button("Generate Insight"):
    if user_query:
        result = get_insight_from_backend(user_query)
        st.write("Insight generated by RAG:")
        st.write(result["insight"])
    else:
        st.warning("Please enter a query!")